

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.event.InternalFrameEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ravi
 */
public class Myhome extends javax.swing.JFrame {

    /**
     *
     */
    public static Coolpad[] c_new=new Coolpad[3];
    public static Terminal[] t_new=new Terminal[3];
    public static RaagPlayer[] r_new=new RaagPlayer[3];
    public static S_Algo[] s_new=new S_Algo[3];
    public static int c_i,t_i,r_i,s_i,c_var,r_var,total_res;
    public static int[] resources=new int[4];
    /**
     * Creates new form Myhome
     */
    public Myhome() {
        c_i=0;
        t_i=0;
        r_i=0;
        s_i=0;
        c_var=0;
        r_var=0;
        total_res=0;
        initComponents();
        for(int i=0;i<3;i++)
            c_new[i]=null;
        for(int i=0;i<3;i++)
            t_new[i]=null;
        for(int i=0;i<3;i++)
            r_new[i]=null;
        for(int i=0;i<3;i++)
            s_new[i]=null;
        for(int i=0;i<4;i++)
            resources[i]=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filechooser = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        desk = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAZARRUS");
        setName("Lazarrus"); // NOI18N
        setSize(new java.awt.Dimension(256, 777));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unnamed.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        desk.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        desk.setDoubleBuffered(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apps-Terminal-Pc-104-icon.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picasion.com_8c95a54fb63c176576178214efba44da.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/music.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cpu.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    // TODO add your handling code here:
                   /* try{
                        Process p = Runtime.getRuntime().exec("javac Mycoolpad.java");
             Process p2 = Runtime.getRuntime().exec("java Mycoolpad");
                    }
                    catch(IOException e) {  
                        e.printStackTrace();  
        }  */
                   //Mycoolpad.main(new String[0]);
                  // this.setVisible(true);
                   //new test().setVisible(true);
                   if(c_i<3){
                   c_new[c_i]=new Coolpad();
                   desk.add(c_new[c_i]);
                   c_new[c_i].show();
                    c_i++;
                   }
                   
                   
                   
    }//GEN-LAST:event_jButton1ActionPerformed
    public static void opencoolpad(String s) throws IOException
    {
        if(c_i<3)
        {
            c_new[c_i]=new Coolpad();
            desk.add(c_new[c_i]);
            c_new[c_i].show();
            c_new[c_i].appendtota(s);
            c_i++;
        }
        else
        {
            if(c_var==3)
                c_var=0;
           // c_new[c_var]=new Coolpad();
            //desk.add(c_new[c_var]);
           // c_new[c_var].show();
           c_new[c_var].appendtota(s);
            c_var++;
        }
        
        /*if(c_new==null)
        {c_new=new Coolpad();
        System.out.println("myhome");
        desk.add(c_new);
        c_new.show();
        c_new.appendtota(s);}
        else
        {
            c_new.appendtota(s);
        }*/
    }
    public static void openplayer(String s) throws IOException
    {
        /*RaagPlayer cpo=new RaagPlayer();
        System.out.println("myhome");
        desk.add(cpo);
        cpo.show();
        cpo.playsong(s);*/
        if(r_i<3)
        {
            r_new[r_i]=new RaagPlayer();
            desk.add(r_new[r_i]);
            r_new[r_i].show();
            r_new[r_i].playsong(s);
            r_i++;
        }
        else
        {
            if(r_var==3)
                r_var=0;
           // c_new[c_var]=new Coolpad();
            //desk.add(c_new[c_var]);
           // c_new[c_var].show();
           r_new[r_var].playsong(s);
            r_var++;
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                    if(t_i<3){
                   t_new[t_i]=new Terminal();
                   desk.add(t_new[t_i]);
                   t_new[t_i].show();
                    t_i++;
                   }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
                if(r_i<3){
                   r_new[r_i]=new RaagPlayer();
                   desk.add(r_new[r_i]);
                   r_new[r_i].show();
                    r_i++;
                   }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        if(r_i<3){
                   s_new[s_i]=new S_Algo();
                   desk.add(s_new[s_i]);
                   s_new[s_i].show();
                    s_i++;
                   }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                filechooser.setDialogTitle("Open File");
                int returnVal = filechooser.showSaveDialog(this);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    File file = filechooser.getSelectedFile();
                    String s=file.getName();
                    if(s.substring(s.lastIndexOf('.')+1).equals("mp3"))
                    {
                         if(r_i<3)
                            {
                                r_new[r_i]=new RaagPlayer();
                                desk.add(r_new[r_i]);
                                r_new[r_i].show();
                                r_new[r_i].playsong(file.getAbsolutePath());
                                r_i++;
                            }
                            else
                            {
                                if(r_var==3)
                                    r_var=0;
                               // c_new[c_var]=new Coolpad();
                                //desk.add(c_new[c_var]);
                               // c_new[c_var].show();
                               r_new[r_var].playsong(file.getAbsolutePath());
                                r_var++;
                            }
                    
                    }
                    else if(s.substring(s.lastIndexOf('.')+1).equals("txt"))
                    {
                        if(c_i<3)
                        {
                            c_new[c_i]=new Coolpad();
                            desk.add(c_new[c_i]);
                            c_new[c_i].show();
                            try {
                                c_new[c_i].appendtota(file.getAbsolutePath());
                            } catch (IOException ex) {
                                Logger.getLogger(Myhome.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            c_i++;
                        }
                        else
                        {
                            if(c_var==3)
                                c_var=0;
                            try {
                                // c_new[c_var]=new Coolpad();
                                //desk.add(c_new[c_var]);
                                // c_new[c_var].show();
                                c_new[c_var].appendtota(file.getAbsolutePath());
                            } catch (IOException ex) {
                                Logger.getLogger(Myhome.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            c_var++;
                        }
                    
                    }
                
                
                }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Myhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Myhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Myhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Myhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Myhome().setVisible(true);
                
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desk;
    private javax.swing.JFileChooser filechooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
