import java.util.Random;
import java.lang.Math;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ravi_prakash
 */
public class Pagefaults extends javax.swing.JFrame {

    int[] pg_rq=new int[100];
    int[] pg_avb=new int[100];
    int[] pg_cnt=new int[100];
    int[] pg_chnc=new int[100];
    int[] d_pg_cnt=new int[100];
    int count=0,i,max,max_i,n=20,count_faults=0,count_1,no_pg;
    Random r=new Random();
    /**
     * Creates new form Pagefaults
     */
    public Pagefaults() {
        initComponents();
        for(i=0;i<n;i++)
        {	pg_rq[i]=r.nextInt(10);
            ta1.append(pg_rq[i]+" ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        t5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("FIFO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LRU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Second Chance");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Optimal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("No of Page Faults");

        jLabel2.setText("Page Faults Algo");

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane2.setViewportView(ta1);

        jLabel3.setText("Pg Table Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        no_pg=Integer.parseInt(t5.getText());
        count=0;
        count_faults=0;
        for(i=0;i<no_pg;i++)
		{
				pg_avb[i]=pg_rq[count];
				pg_cnt[i]=1;
				count++;
				count_faults++;
		}		
		while(count<n)
		{	
			for(i=0;i<no_pg;i++)
			{
				if(pg_avb[i]==pg_rq[count])
					break;
			}
			if(i<no_pg)
			{
				for(int j=0;j<no_pg;j++)
					pg_cnt[j]++;
			}
			else
			{
				max=pg_cnt[0];
				max_i=0;
				for(i=1;i<no_pg;i++)
				{
					if(max<pg_cnt[i])
					{
						max=pg_cnt[i];
						max_i=i;
					}
				}
				for(int j=0;j<no_pg;j++)
					pg_cnt[j]++;
				pg_cnt[max_i]=0;
				pg_avb[max_i]=pg_rq[count];
				count_faults++;
			}
			count++;
		}
		/*for(i=0;i<no_pg;i++)
                {	
                    ta1.append("\n");
                    ta1.append(pg_avb[i]+"\n");
                
                }	*/
		t1.setText(""+count_faults);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        no_pg=Integer.parseInt(t5.getText());
        count=0;
        count_faults=0;
        for(i=0;i<no_pg;i++)
		{
				pg_avb[i]=pg_rq[count];
				pg_cnt[i]=1;
				pg_chnc[i]=0;
				count++;
				count_faults++;
		}		
		while(count<n)
		{	
			//System.out.println(count);
			for(i=0;i<no_pg;i++)				//when page is present in physical memeory
			{						
				if(pg_avb[i]==pg_rq[count])
				{
					pg_chnc[i]=1;
					for(int j=0;j<no_pg;j++)
						pg_cnt[j]++;
					break;
				}
			}
			if(i==no_pg)					//when page is not present in physical memeory
			{
				count_1=0;
				count_faults++;
				for(i=0;i<no_pg;i++)
				{
					if(pg_chnc[i]==1)
					{
						count_1++;
					}	
				}
				if(count_1==no_pg)				//when ref bit of all pages are set
				{
					max=pg_cnt[0];
					max_i=0;
					for(i=1;i<no_pg;i++)
					{
						if(max<pg_cnt[i])
						{
							max=pg_cnt[i];
							max_i=i;
						}
					}
					for(int j=0;j<no_pg;j++)
						pg_cnt[j]++;
					pg_cnt[max_i]=0;
					pg_avb[max_i]=pg_rq[count];
					pg_chnc[max_i]=0;
				}
				else					//when ref bit of all pages are not set
				{
					for(int j=0;j<no_pg;j++)
						d_pg_cnt[j]=pg_cnt[j];
					while(true)
					{
						//if(count<16)
						//System.out.println(count+"*");
						max=d_pg_cnt[0];
						max_i=0;
						for(i=1;i<no_pg;i++)
						{
							if(max<d_pg_cnt[i])
							{
								max=d_pg_cnt[i];
								max_i=i;
							}
						}
						if(pg_chnc[max_i]==0)
						{
							for(int j=0;j<no_pg;j++)
								pg_cnt[j]++;
							pg_cnt[max_i]=0;
							pg_avb[max_i]=pg_rq[count];
							pg_chnc[max_i]=0;
							break;
						}
						else
						{
							pg_chnc[max_i]=0;
							d_pg_cnt[max_i]=0;
					
						}	
					}
				
				}
			
			}
			//for(i=0;i<no_pg;i++)
			//System.out.println(pg_avb[i]+" "+pg_chnc[i]+" "+pg_cnt[i]);
			//System.out.println();
			count++;
		}
		/*for(i=0;i<no_pg;i++)
                {	
                    ta1.append("\n");
                    ta1.append(pg_avb[i]+"\n");
                
                }*/	
		t3.setText(""+count_faults);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        no_pg=Integer.parseInt(t5.getText());
        count=0;
        count_faults=0;
        for(i=0;i<no_pg;i++)
		{
				pg_avb[i]=pg_rq[count];
				pg_cnt[i]=1;
				count++;
				count_faults++;
		}		
		while(count<n)
		{	
			for(i=0;i<no_pg;i++)
			{
				if(pg_avb[i]==pg_rq[count])
					break;
			}
			if(i<no_pg)
			{
				for(int j=0;j<no_pg;j++)
					pg_cnt[j]++;
				pg_cnt[i]=0;
			}
			else
			{
				max=pg_cnt[0];
				max_i=0;
				for(i=1;i<no_pg;i++)
				{
					if(max<pg_cnt[i])
					{
						max=pg_cnt[i];
						max_i=i;
					}
				}
				for(int j=0;j<no_pg;j++)
					pg_cnt[j]++;
				pg_cnt[max_i]=0;
				pg_avb[max_i]=pg_rq[count];
				count_faults++;
				
			}
			count++;
		}
		/*for(i=0;i<no_pg;i++)
                {	
                    ta1.append("\n");
                    ta1.append(pg_avb[i]+"\n");
                
                }*/	
		t2.setText(""+count_faults);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int[] pg_ftr=new int[100];
        no_pg=Integer.parseInt(t5.getText());
        count=0;
        count_faults=0;
        for(i=0;i<no_pg;i++)
		{
				pg_avb[i]=pg_rq[count];
				count++;
				count_faults++;
				pg_ftr[i]=0;
		}		
		while(count<n)
		{	
			for(i=0;i<no_pg;i++)
			{
				if(pg_avb[i]==pg_rq[count])
					break;
			}
			if(i==no_pg)
			{
				for(i=0;i<no_pg;i++)
				{
					for(int j=count;j<n;j++)
					{
						pg_ftr[i]++;
						if(pg_avb[i]==pg_rq[j])
							break;
					}
				}
				max=pg_ftr[0];
				max_i=0;
				for(i=1;i<no_pg;i++)
				{
					if(max<pg_ftr[i])
					{
						max=pg_ftr[i];
						max_i=i;
					}
				}
				for(i=0;i<no_pg;i++)
					pg_ftr[i]=0;
				pg_avb[max_i]=pg_rq[count];
				count_faults++;
			}
			count++;
		}
		/*for(i=0;i<no_pg;i++)
                {	
                    ta1.append("\n");
                    ta1.append(pg_avb[i]+"\n");
                
                }	*/
		t4.setText(""+count_faults);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagefaults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagefaults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagefaults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagefaults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagefaults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
